# Generated by Django 5.1.4 on 2025-01-02 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mi_blog', '0004_alter_comment_active_alter_comment_name'),
    ]

    operations = [
    ]
