# Generated by Django 5.1.4 on 2025-01-06 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mi_blog', '0008_user_bio_user_city_user_preferences'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['-username']},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['-username'], name='mi_blog_use_usernam_083844_idx'),
        ),
    ]
