# Generated by Django 5.1.4 on 2025-01-02 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_blog', '0005_auto_20250102_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios2', to=settings.AUTH_USER_MODEL),
        ),
    ]
