# Generated by Django 5.1.4 on 2025-01-07 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_blog', '0009_alter_user_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
