# Generated by Django 5.1.4 on 2025-01-09 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dark_mode', models.BooleanField(default=False)),
                ('language', models.CharField(default='en', max_length=10)),
                ('timezone', models.CharField(default='UTC', max_length=100)),
                ('date_format', models.CharField(default='YYYY-MM-DD', max_length=50)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('two_factor_auth', models.BooleanField(default=False)),
                ('account_visibility', models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=50)),
                ('theme', models.CharField(choices=[('light', 'Light'), ('dark', 'Dark')], default='light', max_length=50)),
                ('font_size', models.CharField(choices=[('small', 'Small'), ('medium', 'Medium'), ('large', 'Large')], default='medium', max_length=50)),
                ('sidebar_position', models.CharField(choices=[('left', 'Left'), ('right', 'Right')], default='left', max_length=50)),
                ('share_activity', models.BooleanField(default=False)),
                ('data_sharing', models.BooleanField(default=False)),
                ('hide_profile_picture', models.BooleanField(default=False)),
                ('password_expiry_days', models.IntegerField(default=90)),
                ('login_attempts_limit', models.IntegerField(default=5)),
                ('allow_social_logins', models.BooleanField(default=True)),
                ('email_notifications', models.BooleanField(default=True)),
                ('sms_notifications', models.BooleanField(default=False)),
                ('push_notifications', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
