# Generated by Django 5.1.4 on 2025-01-07 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='friendlysent',
            managers=[
            ],
        ),
    ]
