# Generated by Django 5.1.4 on 2025-01-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendlysent_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendlysent',
            name='status',
            field=models.CharField(choices=[('SE', 'SENT'), ('AC', 'ACEPPTED'), ('RE', 'RECHAZED'), ('PE', 'PENDING')], default='SE', max_length=3),
        ),
    ]
